[package]
name = "t5"
version = "0.1.0"
authors = ["Mufaddal Khozema <mufaddal100k@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
text_io = "0.1.7"
prettytable-rs = "^0.8"